export const tagTypes = {
  auth: "auth",
  user: "user",
  profile: "profile",
  category: "category",
  size: "size",
  product: "product",
  order: "order",
  notification: "notification",
  payment: "payment",
  banner: "banner",
  featuredCategory: "featuredCategory",
  setting: "setting",
  staticPage: "staticPage",
  pathaoCity: "PathaoCity",
  pathaoZone: "PathaoZone",
  pathaoArea: "PathaoArea",
  pathaoStore: "PathaoStore",
  pathaoOrder: "PathaoOrder",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.user,
  tagTypes.profile,
  tagTypes.category,
  tagTypes.size,
  tagTypes.product,
  tagTypes.order,
  tagTypes.notification,
  tagTypes.payment,
  tagTypes.banner,
  tagTypes.featuredCategory,
  tagTypes.setting,
  tagTypes.staticPage,
  tagTypes.pathaoCity,
  tagTypes.pathaoZone,
  tagTypes.pathaoArea,
  tagTypes.pathaoStore,
  tagTypes.pathaoOrder,
];
